create table if not exists app_data.app_user
(
        aur_id          bigint                          generated by default as identity not null
,       tnt_id          bigint                                                           not null
,       aur_nm          name                                                             not null
,       rolname         name                                                             not null
,       lng_id          bigint                                                           not null
,       cby             name                            default current_user             not null
,       cts             timestamp with time zone        default now()                    not null
,       uby             name                            default current_user             not null
,       uts             timestamp with time zone        default now()                    not null
,       constraint pk_aur_id      primary key (aur_id)
,       constraint uk_aur_nm      unique      (tnt_id, aur_nm)
,       constraint uk_aur_rolname unique      (rolname)
,       constraint ck_aur_nm      check       ((length(trim(aur_nm)) > 0) and (aur_nm = lower(trim(aur_nm))))
,       constraint ck_aur_rolname check       (rolname = lower(rolname)   and (length(trim(rolname)) > 0))
);
