create table if not exists app_data.app_user_email_address
(
    auea_id bigint                   generated by default as identity not null
,   aur_id  bigint                                                    not null
,   aur_ea  text                                                      not null
,   cby     name                     default current_user             not null
,   cts     timestamp with time zone default now()                    not null
,   uby     name                     default current_user             not null
,   uts     timestamp with time zone default now()                    not null
,   constraint pk_auea   primary key (auea_id)
,   constraint uk_auea   unique      (aur_id, aur_ea)
,   constraint ck_aur_ea check       (length(trim(aur_ea)) > 0)
);
